### ISSUE TITLE
Programm Crash on Windows 10

### ISSUE THREAD

**Issue by TureBentzin** [basti564/MNSPlusTrasher#4]
I can't tell you why but if I open it on a "not MNS+ Computer" the Programm die after 2-3 Minutes!

What I do:

1. Open the File
2. Click on Shares
3. Programm is dead

**Comment by ptrpaws** [comment]
Strange, that's the classical "it works on my machine" situation.
The interesting part is that the Shares menu doesn't "auto runs" any code and I'm using the same code to load it for the "Info" menu.

- Does the program also die when you do nothing for 2-3 minutes?
- Did you click on a button in the "Shares" menu or was it an instant crash?
- Was there an error Message or something similar? 
- Does it also crash when opening the "Info" menu?
- Is it a crash that's exiting the program or does it just hang without response?
- Which .NET framework versions do you have installed? (You can find out with a Program called DotNetVersions)
- Which Windows Version are you using? (I'm testing on 1909, but that normally shouldn't matter)

Btw. thanks for using my software :)
Here is what the menu would normally look like: ![image](https://user-images.githubusercontent.com/34898868/93744440-1e771700-fbf2-11ea-8528-53eaa86b12da.png)
